<?php

namespace Database\Seeders;

use App\Models\Blog;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $blogs = array(
            array('id' => '1','blog_category_id' => '1','title' => 'Blog Title-1','slug' => 'blog-title-1','subtitle' => 'Blog Subtitle-1','description' => '<p>...........It is a long-established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, which makes it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for Lorem Ipsum will uncover many web sites still in their infancy. In various versions, it looks like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for Lorem Ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident and sometimes on purpose (injected humour and the like).</p>','image' => 'upload/blog/20231211121932.jpeg','created_at' => '2024-01-08 07:39:51','updated_at' => '2024-05-20 16:36:20'),
            array('id' => '2','blog_category_id' => '2','title' => 'Blog Title-2','slug' => 'blog-title-2','subtitle' => 'Blog Subtitle-2','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versionhave evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like.','image' => 'upload/blog/20231211122036.jpeg','created_at' => '2024-01-08 07:39:51','updated_at' => '2024-01-08 07:39:51'),
            array('id' => '3','blog_category_id' => '3','title' => 'Blog Title-3','slug' => 'blog-title-3','subtitle' => 'Blog Subtitle-3','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versionhave evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like.3','image' => 'upload/blog/20231211122402.jpg','created_at' => '2024-01-08 07:39:51','updated_at' => '2024-01-08 07:39:51'),
            array('id' => '4','blog_category_id' => '4','title' => 'Blog Title-4','slug' => 'blog-title-4','subtitle' => 'Blog Subtitle-4','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versionhave evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like.4','image' => 'upload/blog/20231211122411.jpg','created_at' => '2024-01-08 07:39:51','updated_at' => '2024-01-08 07:39:51'),
            array('id' => '5','blog_category_id' => '5','title' => 'Blog Title-5','slug' => 'blog-title-5','subtitle' => 'Blog Subtitle-5','description' => 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using Content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versionhave evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like.5','image' => 'upload/blog/20231211122421.jpg','created_at' => '2024-01-08 07:39:51','updated_at' => '2024-01-08 07:39:51'),
            array('id' => '7','blog_category_id' => '1','title' => 'Sholarship','slug' => 'blog-title-7','subtitle' => 'Current University','description' => '<p>Currently, we are providing scholarships in P.H.D., Master and Bachalors 50% for selected universities and programmes only&nbsp;</p>','image' => 'upload/blog/20240302173052.jpg','created_at' => '2024-01-08 07:39:51','updated_at' => '2024-03-02 17:30:52'),
            array('id' => '10','blog_category_id' => '2','title' => 'Test Blog  Category','slug' => 'test-blog-category','subtitle' => 'Test blog','description' => '<p>This is a test blog written by Aminul Islam</p>','image' => 'upload/blog/20240511163342.jpg','created_at' => '2024-05-11 16:33:42','updated_at' => '2024-05-11 16:35:21'),
            array('id' => '11','blog_category_id' => '5','title' => 'Scolarship','slug' => 'scolarship','subtitle' => '50 %','description' => NULL,'image' => 'upload/blog/20240520163837.jpg','created_at' => '2024-05-20 16:38:37','updated_at' => '2024-05-20 16:38:37')
        );

        foreach ($blogs as $blog) {
            Blog::create($blog);
        }

    }
}
