<?php

namespace Database\Seeders;

use App\Models\PageContent;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PageContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $page_contents = array(
            array('id' => '1','page_id' => '8','hints' => 'top-navbar','title' => 'Twitter-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://twitter.com/','is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:31:20','updated_at' => '2024-01-06 11:14:39'),
            array('id' => '2','page_id' => '8','hints' => 'top-navbar','title' => 'Instagram-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.instagram.com/','is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:47:04','updated_at' => '2024-01-06 11:14:32'),
            array('id' => '3','page_id' => '8','hints' => 'top-navbar','title' => 'Facebook-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.facebook.com/','is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:49:29','updated_at' => '2024-01-06 11:14:51'),
            array('id' => '4','page_id' => '8','hints' => 'top-navbar','title' => 'Dribble-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://dribbble.com/','is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:50:09','updated_at' => '2024-01-06 11:15:12'),
            array('id' => '5','page_id' => '8','hints' => 'top-navbar','title' => 'Youtube-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.youtube.com/','is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:50:52','updated_at' => '2024-01-06 11:15:24'),
            array('id' => '6','page_id' => '8','hints' => 'footer','title' => 'Facebook-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.facebook.com/','is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:51:38','updated_at' => '2023-11-08 12:51:38'),
            array('id' => '7','page_id' => '8','hints' => 'footer','title' => 'Instagram-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.instagram.com/','is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:52:18','updated_at' => '2023-11-08 12:52:18'),
            array('id' => '8','page_id' => '8','hints' => 'footer','title' => 'Dribble-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://dribbble.com/','is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:53:11','updated_at' => '2023-11-08 12:53:11'),
            array('id' => '9','page_id' => '8','hints' => 'footer','title' => 'Twitter-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://twitter.com/','is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:53:43','updated_at' => '2023-11-08 12:53:43'),
            array('id' => '10','page_id' => '8','hints' => 'footer','title' => 'Youtube-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.youtube.com/','is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:54:44','updated_at' => '2023-11-08 12:54:44'),
            array('id' => '11','page_id' => '8','hints' => 'footer','title' => 'About','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:56:50','updated_at' => '2023-11-08 12:56:50'),
            array('id' => '12','page_id' => '8','hints' => 'footer','title' => 'Features','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:57:34','updated_at' => '2023-11-08 12:57:34'),
            array('id' => '13','page_id' => '8','hints' => 'footer','title' => 'Pricing','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:58:05','updated_at' => '2023-11-08 12:58:05'),
            array('id' => '14','page_id' => '8','hints' => 'footer','title' => 'Careere','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:58:32','updated_at' => '2023-11-08 12:58:32'),
            array('id' => '15','page_id' => '8','hints' => 'footer','title' => 'Help','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:58:57','updated_at' => '2023-11-08 12:58:57'),
            array('id' => '16','page_id' => '8','hints' => 'footer','title' => 'Privacy Policy','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 12:59:20','updated_at' => '2023-11-08 12:59:20'),
            array('id' => '17','page_id' => '8','hints' => 'footer','title' => '© 2023 WH Doctor\'s Study Lab. All rights reserved','subtitle' => 'copy-right-text','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 13:00:10','updated_at' => '2024-01-06 11:24:08'),
            array('id' => '19','page_id' => '8','hints' => 'menu-item','title' => 'Home','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 13:01:47','updated_at' => '2023-11-08 13:01:47'),
            array('id' => '20','page_id' => '8','hints' => 'menu-item','title' => 'About','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 13:02:14','updated_at' => '2023-11-08 13:02:14'),
            array('id' => '21','page_id' => '8','hints' => 'menu-item','title' => 'Service','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 13:02:38','updated_at' => '2023-11-08 13:02:38'),
            array('id' => '22','page_id' => '8','hints' => 'menu-item','title' => 'Publications','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 13:03:08','updated_at' => '2023-11-08 13:03:08'),
            array('id' => '23','page_id' => '8','hints' => 'menu-item','title' => 'Conference','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 13:03:51','updated_at' => '2023-11-08 13:03:51'),
            array('id' => '24','page_id' => '8','hints' => 'menu-item','title' => 'Accounts','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 13:04:15','updated_at' => '2023-11-08 13:04:15'),
            array('id' => '25','page_id' => '8','hints' => 'menu-item','title' => 'Fly BD','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 13:04:40','updated_at' => '2023-11-08 13:04:40'),
            array('id' => '26','page_id' => '8','hints' => 'menu-item','title' => 'Abroad Living','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-08 13:05:04','updated_at' => '2023-11-08 13:05:04'),
            array('id' => '28','page_id' => '1','hints' => 'about-section','title' => 'Welcome to WH Doctors Study Lab Ltd','subtitle' => 'Know your study before starting','image' => NULL,'description' => '<p><span style="color:#cc0000"><strong><span style="font-family:Georgia,serif"><span style="font-size:16px">WH Doctor Study Lab</span></span></strong></span> is an overseas education consulting firm that helps students study abroad. Through the WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia. The experienced team at WH Doctor Study Lab offers authentic and resourceful information and solutions to students interested in studying abroad. The experienced and well-trained counsellors at WH Doctor Study Lab are dedicated to offering multiple services and help to the students whenever they need it. They have real-life experience studying abroad. Moreover, they get training from the experts to stay up-to-date with their knowledge. edited</p>
        
            <p>&nbsp;</p>
        
            <h1>Free Education counselling</h1>
        
            <p>WH Doctor Study Lab is an overseas education consulting firm that helps students study abroad. Through the WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>
        
            <p>&nbsp;</p>
        
            <h1>Student Admission Services</h1>
        
            <p>WH Doctor Study Lab is an overseas education consulting firm that helps students study abroad. Through the WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>
        
            <p>&nbsp;</p>
        
            <h1>Free Education counselling</h1>
        
            <p>WH Doctor Study Lab is an overseas education consulting firm that helps students study abroad. Through the WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>
        
            <p>&nbsp;</p>
        
            <h1>Student Admission Services</h1>
        
            <p>WH Doctor Study Lab is an overseas education consulting firm that helps students study abroad. Through the WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>
        
            <p>&nbsp;</p>
        
            <h1>Free Education counselling</h1>
        
            <p>WH Doctor Study Lab is an overseas education consulting firm that helps students study abroad. Through the WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>
        
            <p>&nbsp;</p>
        
            <h1>Student Admission Services</h1>
        
            <p>WH Doctor Study Lab is an overseas education consulting firm that helps students study abroad. Through the WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 03:39:30','updated_at' => '2024-05-11 21:31:23'),
            array('id' => '35','page_id' => '8','hints' => 'Under-about-section-box','title' => 'Universities','subtitle' => 'We are working world leading Universities','image' => 'upload/pageContent-image/20240304174952.png','description' => '<p>200</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 04:21:45','updated_at' => '2024-03-05 00:03:05'),
            array('id' => '36','page_id' => '8','hints' => 'Under-about-section-box','title' => 'Service Point','subtitle' => 'A large number of service point all over the world','image' => 'upload/pageContent-image/20240304175558.png','description' => '<p>8&nbsp;</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 04:22:29','updated_at' => '2024-03-05 00:03:38'),
            array('id' => '37','page_id' => '8','hints' => 'Under-about-section-box','title' => 'Cities','subtitle' => 'Prime location','image' => 'upload/pageContent-image/20240304180121.png','description' => '<p>12</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 04:23:11','updated_at' => '2024-03-05 00:03:48'),
            array('id' => '38','page_id' => '1','hints' => 'clientreview-section','title' => 'What they’re saying','subtitle' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non volutpat turpis. Mauris luctus rutrum mi ut rhoncus. Integer in dignissim tortor.','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 04:24:58','updated_at' => '2024-01-06 08:07:15'),
            array('id' => '39','page_id' => '1','hints' => 'Customer Reviw Section-box-01','title' => 'Aminul Islam','subtitle' => 'Student from Dhaka','image' => 'upload/pageContent-image/20240511154605.jpg','description' => 'WH Doctors Study lab Ltd. . is a best service provider as a student consultant in Asia, specially in Banagladesh and Malaysia','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 04:30:48','updated_at' => '2024-05-11 21:47:17'),
            array('id' => '40','page_id' => '1','hints' => 'Customer Reviw Section-box-02','title' => 'Jane Doe','subtitle' => 'Student from China','image' => 'upload/pageContent-image/20231228124056.jpg','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lorem lorem, malesuada in metus vitae, scelerisque accumsan ipsum. Nam pellentesque nulla leo, sagittis vehicula sem commodo nec. edited','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 04:31:37','updated_at' => '2024-05-11 21:47:33'),
            array('id' => '41','page_id' => '1','hints' => 'Customer Reviw Section-box-03','title' => 'Xin Lie','subtitle' => NULL,'image' => 'upload/pageContent-image/20231228124104.jpg','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lorem lorem, malesuada in metus vitae, scelerisque accumsan ipsum. Nam pellentesque nulla leo, sagittis vehicula sem commodo nec.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 04:32:19','updated_at' => '2024-05-11 21:48:41'),
            array('id' => '42','page_id' => '1','hints' => 'clientreview-bottomsection','title' => 'Know your Study before Starting with us','subtitle' => 'Free consulting, Free Visa process and one to one meeting to clearify your future destination','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 04:33:23','updated_at' => '2024-03-02 23:04:42'),
            array('id' => '43','page_id' => '1','hints' => 'whyus-section','title' => 'WHY CHOSE US?','subtitle' => NULL,'image' => NULL,'description' => '<p><strong>Free consulting</strong>, more then 5 countries service centres,&nbsp; fast response, No hidden charges, all the admission procedures are free for all - Edited</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 04:40:50','updated_at' => '2024-05-11 21:49:44'),
            array('id' => '44','page_id' => '1','hints' => 'whyus-section','title' => 'High Visa Success Rate','subtitle' => NULL,'image' => 'upload/pageContent-image/20231109050118.png','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:01:18','updated_at' => '2024-01-06 07:57:32'),
            array('id' => '45','page_id' => '1','hints' => 'whyus-section','title' => 'Located in 5 Countries','subtitle' => NULL,'image' => 'upload/pageContent-image/20231109050206.png','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:02:06','updated_at' => '2024-01-06 07:57:49'),
            array('id' => '46','page_id' => '1','hints' => 'whyus-section','title' => '50+ Partner Institutions','subtitle' => NULL,'image' => 'upload/pageContent-image/20231109050302.png','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:03:02','updated_at' => '2024-01-06 07:58:02'),
            array('id' => '47','page_id' => '1','hints' => 'whyus-section','title' => 'End to End Services','subtitle' => NULL,'image' => 'upload/pageContent-image/20231109050340.png','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:03:40','updated_at' => '2024-01-06 07:58:13'),
            array('id' => '48','page_id' => '1','hints' => 'apply-section','title' => 'Plan Your Best Education in Top Foreign Universities','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:05:17','updated_at' => '2024-01-06 08:20:59'),
            array('id' => '59','page_id' => '1','hints' => 'home-contact-social','title' => 'Facebook-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.facebook.com/','is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:22:33','updated_at' => '2023-11-09 05:22:33'),
            array('id' => '60','page_id' => '1','hints' => 'home-contact-social','title' => 'Twitter-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://twitter.com/','is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:23:11','updated_at' => '2023-11-09 05:23:11'),
            array('id' => '61','page_id' => '1','hints' => 'home-contact-social','title' => 'Youtube','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.youtube.com/channel/UCiIW3cM51ITTt6015ZC4HBA','is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:23:44','updated_at' => '2024-02-20 22:31:26'),
            array('id' => '62','page_id' => '1','hints' => 'home-contact-social','title' => 'Wechat','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://web.wechat.com/?lang=en wxid_eog54z3kyw512','is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:24:22','updated_at' => '2024-02-20 22:36:47'),
            array('id' => '63','page_id' => '1','hints' => 'leading-university','title' => 'Leading Universities','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:25:32','updated_at' => '2024-01-06 10:13:31'),
            array('id' => '76','page_id' => '1','hints' => 'blog-news','title' => 'Blog & News','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:39:16','updated_at' => '2023-11-09 05:39:16'),
            array('id' => '79','page_id' => '2','hints' => 'About-us-heading','title' => 'ABOUT US','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:48:21','updated_at' => '2024-01-07 07:56:37'),
            array('id' => '80','page_id' => '2','hints' => 'About-Button','title' => 'About us','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:51:56','updated_at' => '2024-01-07 07:57:07'),
            array('id' => '81','page_id' => '2','hints' => 'About-Button','title' => 'Message From Chairman','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:52:25','updated_at' => '2024-01-07 07:57:14'),
            array('id' => '82','page_id' => '2','hints' => 'About-Button','title' => 'Message From Managing Director','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:52:54','updated_at' => '2024-01-07 07:57:20'),
            array('id' => '83','page_id' => '2','hints' => 'About-About','title' => 'W H Doctors Study Lab Ltd.','subtitle' => 'We help you to study in Abroad.','image' => 'upload/pageContent-image/20231109055414.png','description' => '<p>Study Abroad also has a well-organised platform in Bangladesh for student training for the preparation of IELTS and other relevant English language tests. We have liaison branches all over Bangladesh. No other educational training institute in Bangladesh has either such a vast network or student access as we do. This exclusive student base we currently have possesses great potential for overseas student recruitment. Our various services are comprehensive and tailored to suit students&rsquo; needs and budgets. All of our services aim to provide a student with personalised advice and information to help avoid unnecessary expenses until we are confident that a visa application by a student recruited by us has the best possible chance of success.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:54:14','updated_at' => '2024-03-04 23:33:35'),
            array('id' => '84','page_id' => '2','hints' => 'About-Mission','title' => 'Our Mission Statement','subtitle' => NULL,'image' => NULL,'description' => '<p>Most educators agree that immersion experiences are among the most lasting and meaningful types of education. Since our founding in 1970, we stand by our mission: &ldquo;International Field Studies is a non-profit organisation providing environmental education, scientific research, and cultural awareness through experiential learning.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:56:14','updated_at' => '2024-03-04 23:31:12'),
            array('id' => '85','page_id' => '2','hints' => 'About-What-we-do','title' => 'Our Services','subtitle' => NULL,'image' => NULL,'description' => '<p>International Field Studies, Inc. (IFS) is an educational and scientific non-profit organisation established to promote and assist educators with field study programmes. Established in 1970, IFS grew out of the increasing teacher interest in implementing field study experiences for their students with minimal organisational difficulty and expense. International Field Studies offers secondary schools, university groups, scientists, and other special-interest organisations field studies in four programme areas..... IFS continues to promote the concept of field studies as an important educational method. These experiential, outside-of-the classroom learning experiences are successful in almost every discipline, including the natural sciences, creative arts, history, and physical education. IFS believes an interdisciplinary approach to learning is especially well suited to the field studies environment. IFS functions as a facilitator for educational groups seeking expertise and logistical support. Staff members, experienced field instructors, and resource materials are available to assist educators and group leaders with educational development, site planning, and budgeting for a successful comprehensive field programme. By working with IFS to develop a proposed field study, teachers are able to offer their students high quality field study opportunities.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 05:56:55','updated_at' => '2024-03-04 23:34:50'),
            array('id' => '86','page_id' => '2','hints' => 'Sidebar-university-heading','title' => 'Find Your Next Destination...','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 06:04:39','updated_at' => '2024-01-07 09:12:22'),
            array('id' => '92','page_id' => '2','hints' => 'Manage-app-heading','title' => 'Manage your projects from your mobile','subtitle' => 'Download the app to manage your projects, keep track of the progress and complete tasks without procastinating. Stay on track and complete on time!','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 06:25:50','updated_at' => '2024-01-07 07:59:13'),
            // array('id' => '101','page_id' => '4','hints' => 'Hero section abroad','title' => 'STUDY ABROAD','subtitle' => NULL,'image' => 'upload/pageContent-image/20231109074238.jpeg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 07:42:38','updated_at' => '2024-01-06 12:57:10'),
            // array('id' => '103','page_id' => '5','hints' => 'Information section About Button','title' => 'Required Pepper\'s','subtitle' => 'The documents you need for your visa application depend on your situation and the course you are planning to study and the nature of employment of your sponsor. However, in general, you need the following documents:','image' => NULL,'description' => '<p>A valid LOA (Letter of Acceptance) from a Canadian educational institution</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 07:48:26','updated_at' => '2024-03-04 23:40:00'),
            // array('id' => '104','page_id' => '5','hints' => 'Information section About Button','title' => 'Application Information','subtitle' => 'Intakes, English Language Requirements, Diploma - Advanced Diploma','image' => NULL,'description' => 'International students are anticipated to begin planning for their research in Canada one year in advance. The most important intake for Canada usually is \'Fall\' i.e September. The different intake is in the month of \'Winter\' i.e. January, however, it relies upon the program and the institution. Very few institutes have May intake as well.
                                                                                            
            //                                                                                                     All students have to be fluent in English if they\'re applying to Canadian Institutes. International students want to have a specified degree of English language competence. All students ought to take the IELTS or TOEFL(ibt) exams. An IELTS band of 6.5 for Undergraduate & 6.5/7 for Postgraduate publications or a TOEFL rating of eighty and above for Undergraduate and ninety and above for Post Graduate courses is desirable. For Diploma and Advanced Diploma 6.0 in IELTS or equal different tests, a rating is required.
                                                                                            
            //                                                                                                     GPA 3.0 to 5.0 in HSC / Min 4-5C in O Level with C in Math','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 07:50:19','updated_at' => '2023-11-09 07:50:19'),
            // array('id' => '105','page_id' => '5','hints' => 'Information section About Button','title' => 'Visa Information','subtitle' => 'Points required to gain Tier four, General Student Visa:','image' => NULL,'description' => 'To efficiently apply for a Tier four General visa, you have to need to score forty out of forty points.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','active_status' => '1','created_at' => '2023-11-09 07:51:01','updated_at' => '2023-11-16 04:10:30'),
            array('id' => '107','page_id' => '1','hints' => 'about-section','title' => 'Welcome to WH Doctors Study Lab Ltd','subtitle' => 'Know your study before starting','image' => NULL,'description' => '<p>WH Doctor Study Lab is an overseas education consulting firm that helps students study abroad. Through the WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia. The experienced team at WH Doctor Study Lab offers authentic and resourceful information and solutions to students interested in studying abroad. The experienced and well-trained counsellors at WH Doctor Study Lab are dedicated to offering multiple services and help to the students whenever they need it. They have real-life experience studying abroad. Moreover, they get training from the experts to stay up-to-date with their knowledge.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-16 06:28:28','updated_at' => '2024-02-20 23:31:25'),
            array('id' => '114','page_id' => '1','hints' => 'about-section','title' => 'Welcome to WH Doctors Services Point','subtitle' => 'Know your study before starting','image' => NULL,'description' => '<p>WH Doctor Study Lab is an overseas education consulting firm that helps students study abroad. Through the WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia. The experienced team at WH Doctor Study Lab offers authentic and resourceful information and solutions to students interested in studying abroad. The experienced and well-trained counsellors at WH Doctor Study Lab are dedicated to offering multiple services and help to the students whenever they need it. They have real-life experience studying abroad. Moreover, they get training from the experts to stay up-to-date with their knowledge.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-16 06:38:00','updated_at' => '2024-03-04 23:19:34'),
            array('id' => '115','page_id' => '1','hints' => 'about-section','title' => 'Welcome to WH Doctors Contact','subtitle' => 'Know your study before starting','image' => NULL,'description' => '<p><span style="font-size:16px"><span style="font-family:Comic Sans MS,cursive"><strong>WH Doctor Study Lab is an overseas education consulting firm that helps students study abroad</strong></span></span>. Through the WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia. The experienced team at WH Doctor Study Lab offers authentic and resourceful information and solutions to students interested in studying abroad. The experienced and well-trained counsellors at WH Doctor Study Lab are dedicated to offering multiple services and help to the students whenever they need it. They have real-life experience studying abroad. Moreover, they get training from the experts to stay up-to-date with their knowledge. edited</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-16 06:38:38','updated_at' => '2024-05-11 21:42:11'),
            array('id' => '118','page_id' => '1','hints' => 'slider','title' => 'W H Doctor Study Lab Ltd.','subtitle' => 'Know your study before starting','image' => 'upload/pageContent-image/20240220164523.jpeg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-02-20 22:48:59'),
            array('id' => '119','page_id' => '1','hints' => 'slider','title' => 'W H Doctor Study Lab Ltd.','subtitle' => 'Know your study before starting','image' => 'upload/pageContent-image/20240220164731.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-02-20 22:48:49'),
            array('id' => '120','page_id' => '1','hints' => 'slider','title' => 'W H Doctor Study Lab Ltd.','subtitle' => 'Know your study before starting','image' => 'upload/pageContent-image/20240220164251.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-02-20 22:49:21'),
            array('id' => '121','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab Ltd.','subtitle' => 'Know your study before starting','image' => 'upload/pageContent-image/20231210063004.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-02-20 22:49:41'),
            array('id' => '122','page_id' => '1','hints' => 'slider','title' => 'Universiti Putra Malaysia (UPM)','subtitle' => 'We Love UPM','image' => 'upload/pageContent-image/20240511152230.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-05-11 21:22:30'),
            array('id' => '123','page_id' => '1','hints' => 'home-seo','title' => 'WH Doctors Home page','subtitle' => 'WH Doctors, WH, Doctors, Abroad Education','image' => 'upload/pageContent-image/20240108041742.png','description' => 'Description for WH Doctors Home page','number' => NULL,'button_text' => 'seo','button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-01-08 04:17:42','updated_at' => '2024-01-08 04:17:42'),
            array('id' => '124','page_id' => '2','hints' => 'about-seo','title' => 'WH Doctors About page','subtitle' => 'WH Doctors, WH, Doctors, Abroad Education','image' => 'upload/pageContent-image/20240108042200.png','description' => '<p>Description for WH Doctors About page</p>','number' => NULL,'button_text' => 'seo','button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-01-08 04:22:00','updated_at' => '2024-03-04 23:38:35'),
            array('id' => '125','page_id' => '3','hints' => 'service-seo','title' => 'WH Doctors Service Category page','subtitle' => 'WH Doctors, WH, Doctors, Abroad Education, Service Category','image' => 'upload/pageContent-image/20240108042500.png','description' => '<p>Description for WH Doctors Service Category page</p>','number' => NULL,'button_text' => 'seo','button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-01-08 04:25:00','updated_at' => '2024-03-04 23:40:20'),
            array('id' => '126','page_id' => '4','hints' => 'study-abroad-seo','title' => 'WH Doctors Study Abroad page','subtitle' => 'WH Doctors, WH, Doctors, Abroad Education, Study Abroad','image' => 'upload/pageContent-image/20240108043332.png','description' => '<p>Description for WH Doctors Study abroad page</p>','number' => NULL,'button_text' => 'seo','button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-01-08 04:33:32','updated_at' => '2024-03-05 00:04:32'),
            array('id' => '127','page_id' => '4','hints' => 'abroad-university-seo','title' => 'WH Doctors Abroad University page','subtitle' => 'WH Doctors, WH, Doctors, Abroad Education, Abroad University','image' => 'upload/pageContent-image/20240108044500.png','description' => 'Description for WH Doctors Abroad University page','number' => NULL,'button_text' => 'seo','button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-01-08 04:35:32','updated_at' => '2024-01-08 04:35:32'),
            array('id' => '128','page_id' => '1','hints' => 'contact-section','title' => 'Contact Information','subtitle' => 'Fill up the form and our Team will get back to you within 24 hours.','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-02-04 08:08:57','updated_at' => '2024-02-04 08:08:57'),
            array('id' => '129','page_id' => '9','hints' => 'conference-section','title' => 'Conference','subtitle' => NULL,'image' => NULL,'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-02-04 08:57:11','updated_at' => '2024-02-04 08:57:11'),
            array('id' => '130','page_id' => '9','hints' => 'conference-seo','title' => 'WH Doctors Conference page','subtitle' => 'WH Doctors, WH, Doctors, Conference','image' => 'upload/pageContent-image/20240204085925.png','description' => 'Description for WH Doctors Conference page','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-02-04 08:59:25','updated_at' => '2024-02-04 08:59:25'),
            array('id' => '131','page_id' => '10','hints' => 'flybd-section','title' => 'FLY BD','subtitle' => NULL,'image' => NULL,'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-02-04 09:03:07','updated_at' => '2024-02-04 09:03:07'),
            array('id' => '132','page_id' => '10','hints' => 'flybd-seo','title' => 'WH Doctors FlyBD page','subtitle' => 'WH Doctors, WH, Doctors, FlyBD','image' => 'upload/pageContent-image/20240204090506.png','description' => 'Description for WH Doctors FlyBD page','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-02-04 09:05:06','updated_at' => '2024-02-04 09:05:06'),
            array('id' => '133','page_id' => '1','hints' => 'service-point','title' => 'Service Point Malaysia - 1','subtitle' => NULL,'image' => NULL,'description' => '<p>102, Selangor; Kuala Lumpur; Malaysia&nbsp; : edited</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-02-04 10:10:48','updated_at' => '2024-05-11 21:39:27'),
            array('id' => '134','page_id' => '1','hints' => 'service-point','title' => 'Service Point Malaysia KL  -2','subtitle' => NULL,'image' => NULL,'description' => '<p>Twin tower, KL</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-02-04 10:11:42','updated_at' => '2024-05-11 21:37:20'),
            array('id' => '135','page_id' => '1','hints' => 'service-point','title' => 'Service Point Dhaka  -3','subtitle' => NULL,'image' => NULL,'description' => '<p>House 144, Road 11, Sector 13, Uttara&nbsp;Dhaka 1230&nbsp;</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-02-04 10:12:06','updated_at' => '2024-02-20 23:37:07'),
            array('id' => '136','page_id' => '1','hints' => 'service-point','title' => 'Service Point Guilin Provience  -4','subtitle' => NULL,'image' => NULL,'description' => '<p>Guilin Province, China&nbsp;</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '1','created_at' => '2024-02-04 10:12:24','updated_at' => '2024-02-20 23:38:37'),
            array('id' => '137','page_id' => '1','hints' => 'service-point','title' => 'Service Point -5','subtitle' => NULL,'image' => NULL,'description' => '<p>In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 10:10:48','updated_at' => '2024-02-04 10:32:45'),
            array('id' => '138','page_id' => '1','hints' => 'service-point','title' => 'Service Point -6','subtitle' => NULL,'image' => NULL,'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 10:11:42','updated_at' => '2024-02-04 10:11:42'),
            array('id' => '139','page_id' => '1','hints' => 'service-point','title' => 'Service Point -7','subtitle' => NULL,'image' => NULL,'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '0','created_at' => '2024-02-04 10:12:06','updated_at' => '2024-02-04 10:12:06'),
            array('id' => '140','page_id' => '1','hints' => 'service-point','title' => 'Service Point -8','subtitle' => NULL,'image' => NULL,'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '0','created_at' => '2024-02-04 10:12:24','updated_at' => '2024-02-04 10:12:24'),
            array('id' => '141','page_id' => '1','hints' => 'service-point','title' => 'Service Point -9','subtitle' => NULL,'image' => NULL,'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '0','created_at' => '2024-02-04 10:12:24','updated_at' => '2024-02-04 10:12:24'),
            array('id' => '142','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab 6','subtitle' => 'an education consulting firm','image' => 'upload/pageContent-image/20231210062965.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '0','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-01-06 05:59:48'),
            array('id' => '143','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab 7','subtitle' => 'an education consulting firm','image' => 'upload/pageContent-image/20231210062976.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0', 'active_status' => '0', 'created_at' => '2023-11-18 15:02:11','updated_at' => '2024-01-06 06:02:06'),
            array('id' => '144','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab 8','subtitle' => 'an education consulting firm','image' => 'upload/pageContent-image/20231210062995.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0', 'active_status' => '0', 'created_at' => '2023-11-18 15:02:11','updated_at' => '2024-01-06 06:02:14'),
            array('id' => '145','page_id' => '11','hints' => 'abroad-living-section','title' => 'Abroad Living','subtitle' => NULL,'image' => NULL,'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 09:03:07','updated_at' => '2024-02-04 09:03:07'),
            array('id' => '146','page_id' => '11','hints' => 'abroad-living-seo','title' => 'WH Doctors Abroad Living page','subtitle' => 'WH Doctors, WH, Doctors, FlyBD','image' => 'upload/pageContent-image/20240204090506.png','description' => 'Description for WH Doctors FlyBD page','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 09:05:06','updated_at' => '2024-02-04 09:05:06'),
        );

        // $page_contents = array(
        //     array('id' => '1','page_id' => '8','hints' => 'top-navbar','title' => 'Twitter-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://twitter.com/','is_not_deleteable' => '0','created_at' => '2023-11-08 12:31:20','updated_at' => '2024-01-06 11:14:39'),
        //     array('id' => '2','page_id' => '8','hints' => 'top-navbar','title' => 'Instagram-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.instagram.com/','is_not_deleteable' => '0','created_at' => '2023-11-08 12:47:04','updated_at' => '2024-01-06 11:14:32'),
        //     array('id' => '3','page_id' => '8','hints' => 'top-navbar','title' => 'Facebook-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.facebook.com/','is_not_deleteable' => '0','created_at' => '2023-11-08 12:49:29','updated_at' => '2024-01-06 11:14:51'),
        //     array('id' => '4','page_id' => '8','hints' => 'top-navbar','title' => 'Dribble-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://dribbble.com/','is_not_deleteable' => '0','created_at' => '2023-11-08 12:50:09','updated_at' => '2024-01-06 11:15:12'),
        //     array('id' => '5','page_id' => '8','hints' => 'top-navbar','title' => 'Youtube-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.youtube.com/','is_not_deleteable' => '0','created_at' => '2023-11-08 12:50:52','updated_at' => '2024-01-06 11:15:24'),
        //     array('id' => '6','page_id' => '8','hints' => 'footer','title' => 'Facebook-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.facebook.com/','is_not_deleteable' => '0','created_at' => '2023-11-08 12:51:38','updated_at' => '2023-11-08 12:51:38'),
        //     array('id' => '7','page_id' => '8','hints' => 'footer','title' => 'Instagram-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.instagram.com/','is_not_deleteable' => '0','created_at' => '2023-11-08 12:52:18','updated_at' => '2023-11-08 12:52:18'),
        //     array('id' => '8','page_id' => '8','hints' => 'footer','title' => 'Dribble-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://dribbble.com/','is_not_deleteable' => '0','created_at' => '2023-11-08 12:53:11','updated_at' => '2023-11-08 12:53:11'),
        //     array('id' => '9','page_id' => '8','hints' => 'footer','title' => 'Twitter-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://twitter.com/','is_not_deleteable' => '0','created_at' => '2023-11-08 12:53:43','updated_at' => '2023-11-08 12:53:43'),
        //     array('id' => '10','page_id' => '8','hints' => 'footer','title' => 'Youtube-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.youtube.com/','is_not_deleteable' => '0','created_at' => '2023-11-08 12:54:44','updated_at' => '2023-11-08 12:54:44'),
        //     array('id' => '11','page_id' => '8','hints' => 'footer','title' => 'About','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 12:56:50','updated_at' => '2023-11-08 12:56:50'),
        //     array('id' => '12','page_id' => '8','hints' => 'footer','title' => 'Features','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 12:57:34','updated_at' => '2023-11-08 12:57:34'),
        //     array('id' => '13','page_id' => '8','hints' => 'footer','title' => 'Pricing','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 12:58:05','updated_at' => '2023-11-08 12:58:05'),
        //     array('id' => '14','page_id' => '8','hints' => 'footer','title' => 'Careere','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 12:58:32','updated_at' => '2023-11-08 12:58:32'),
        //     array('id' => '15','page_id' => '8','hints' => 'footer','title' => 'Help','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 12:58:57','updated_at' => '2023-11-08 12:58:57'),
        //     array('id' => '16','page_id' => '8','hints' => 'footer','title' => 'Privacy Policy','subtitle' => 'menu-item','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 12:59:20','updated_at' => '2023-11-08 12:59:20'),
        //     array('id' => '17','page_id' => '8','hints' => 'footer','title' => '© 2023 WH Doctor\'s Study Lab. All rights reserved','subtitle' => 'copy-right-text','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 13:00:10','updated_at' => '2024-01-06 11:24:08'),
        //     array('id' => '19','page_id' => '8','hints' => 'menu-item','title' => 'Home','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 13:01:47','updated_at' => '2023-11-08 13:01:47'),
        //     array('id' => '20','page_id' => '8','hints' => 'menu-item','title' => 'About','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 13:02:14','updated_at' => '2023-11-08 13:02:14'),
        //     array('id' => '21','page_id' => '8','hints' => 'menu-item','title' => 'Service','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 13:02:38','updated_at' => '2023-11-08 13:02:38'),
        //     array('id' => '22','page_id' => '8','hints' => 'menu-item','title' => 'Publications','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 13:03:08','updated_at' => '2023-11-08 13:03:08'),
        //     array('id' => '23','page_id' => '8','hints' => 'menu-item','title' => 'Conference','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 13:03:51','updated_at' => '2023-11-08 13:03:51'),
        //     array('id' => '24','page_id' => '8','hints' => 'menu-item','title' => 'Accounts','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 13:04:15','updated_at' => '2023-11-08 13:04:15'),
        //     array('id' => '25','page_id' => '8','hints' => 'menu-item','title' => 'Fly BD','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 13:04:40','updated_at' => '2023-11-08 13:04:40'),
        //     array('id' => '26','page_id' => '8','hints' => 'menu-item','title' => 'Abroad Living','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-08 13:05:04','updated_at' => '2023-11-08 13:05:04'),
        //     array('id' => '28','page_id' => '1','hints' => 'about-section','title' => 'Welcome to WH Doctors Study Lab Ltd','subtitle' => 'Lorem ipsum is common placeholder text used to demonstrate','image' => NULL,'description' => '<p>WH Doctor Study Lab is an overseas education consulting firm that helps students to study abroad. Through WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia. The experienced team of WH Doctor Study Lab offers authentic and resourceful information and solutions to students interested in studying abroad. The experienced and well-trained counsellors of WH Doctor Study Lab are dedicated to offering multiple services and help to the students anytime they need it. They have real-life experience studying abroad. Moreover, they get training from the experts to be up-to-date with their knowledge.</p>
                                                                      
        //                                                                   <p>&nbsp;</p>
                                                                      
        //                                                                   <h1>Free Education Counselling</h1>
                                                                      
        //                                                                   <p>WH Doctor Study Lab is an overseas education consulting firm that helps students to study abroad. Through WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>
                                                                      
        //                                                                   <p>&nbsp;</p>
                                                                      
        //                                                                   <h1>Student Admission Services</h1>
                                                                      
        //                                                                   <p>WH Doctor Study Lab is an overseas education consulting firm that helps students to study abroad. Through WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>
                                                                      
        //                                                                   <p>&nbsp;</p>
                                                                      
        //                                                                   <h1>Free Education Counselling</h1>
                                                                      
        //                                                                   <p>WH Doctor Study Lab is an overseas education consulting firm that helps students to study abroad. Through WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>
                                                                      
        //                                                                   <p>&nbsp;</p>
                                                                      
        //                                                                   <h1>Student Admission Services</h1>
                                                                      
        //                                                                   <p>WH Doctor Study Lab is an overseas education consulting firm that helps students to study abroad. Through WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>
                                                                      
        //                                                                   <p>&nbsp;</p>
                                                                      
        //                                                                   <h1>Free Education Counselling</h1>
                                                                      
        //                                                                   <p>WH Doctor Study Lab is an overseas education consulting firm that helps students to study abroad. Through WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>
                                                                      
        //                                                                   <p>&nbsp;</p>
                                                                      
        //                                                                   <h1>Student Admission Services</h1>
                                                                      
        //                                                                   <p>WH Doctor Study Lab is an overseas education consulting firm that helps students to study abroad. Through WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 03:39:30','updated_at' => '2024-01-06 15:47:59'),
        //     array('id' => '35','page_id' => '8','hints' => 'Under-about-section-box','title' => 'Customers','subtitle' => 'Lorem ipsum dolor sit amet.','image' => 'upload/pageContent-image/20231109042144.png','description' => '<p>50</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 04:21:45','updated_at' => '2024-01-07 09:32:34'),
        //     array('id' => '36','page_id' => '8','hints' => 'Under-about-section-box','title' => 'Projects','subtitle' => 'Lorem ipsum dolor sit amet.','image' => 'upload/pageContent-image/20231109042229.png','description' => '<p>300</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 04:22:29','updated_at' => '2024-01-07 09:32:42'),
        //     array('id' => '37','page_id' => '8','hints' => 'Under-about-section-box','title' => 'Cities','subtitle' => 'Lorem ipsum dolor sit amet.','image' => 'upload/pageContent-image/20231109042311.png','description' => '<p>20</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 04:23:11','updated_at' => '2024-01-07 09:32:50'),
        //     array('id' => '38','page_id' => '1','hints' => 'clientreview-section','title' => 'What they’re saying','subtitle' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non volutpat turpis. Mauris luctus rutrum mi ut rhoncus. Integer in dignissim tortor.','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 04:24:58','updated_at' => '2024-01-06 08:07:15'),

        //     // array('id' => '39','page_id' => '1','hints' => 'Customer Reviw Section-box-01','title' => 'Jane Doe','subtitle' => 'SOFTWARE ENGINEER','image' => 'upload/pageContent-image/20231228123836.jpg','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lorem lorem, malesuada in metus vitae, scelerisque accumsan ipsum. Nam pellentesque nulla leo, sagittis vehicula sem commodo nec.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 04:30:48','updated_at' => '2023-12-28 12:38:36'),
            
        //     // array('id' => '40','page_id' => '1','hints' => 'Customer Reviw Section-box-02','title' => 'Jane Doe','subtitle' => 'SOFTWARE ENGINEER','image' => 'upload/pageContent-image/20231228124056.jpg','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lorem lorem, malesuada in metus vitae, scelerisque accumsan ipsum. Nam pellentesque nulla leo, sagittis vehicula sem commodo nec.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 04:31:37','updated_at' => '2023-12-28 12:40:56'),
        //     // array('id' => '41','page_id' => '1','hints' => 'Customer Reviw Section-box-03','title' => 'Jane Doe','subtitle' => 'SOFTWARE ENGINEER','image' => 'upload/pageContent-image/20231228124104.jpg','description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In lorem lorem, malesuada in metus vitae, scelerisque accumsan ipsum. Nam pellentesque nulla leo, sagittis vehicula sem commodo nec.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 04:32:19','updated_at' => '2023-12-28 12:41:04'),
            
            
        //     array('id' => '42','page_id' => '1','hints' => 'clientreview-bottomsection','title' => 'Enter the world of all fashion trends','subtitle' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Condimentum diam orci pretium a pharetra, feugiat cursus. Dictumst risus, sem egestas odio cras adipiscing vulputate. Nisi, risus in suscipit non. Non commodo volutpat, pharetra, vel.','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 04:33:23','updated_at' => '2024-01-07 08:03:53'),
        //     array('id' => '43','page_id' => '1','hints' => 'whyus-section','title' => 'WHY US?','subtitle' => NULL,'image' => NULL,'description' => '<p>Like you, a remarkable number of international students from across the world, from diverse backgrounds, have achieved their international education goals successfully through us. Our ethical, accurate &amp; friendly guidance in the last 15 years has been the recipe. Now, it&#39;s your turn. Tell us your dreams, we will get you there.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 04:40:50','updated_at' => '2024-01-06 07:56:37'),
        //     array('id' => '44','page_id' => '1','hints' => 'whyus-section','title' => 'High Visa Success Rate','subtitle' => NULL,'image' => 'upload/pageContent-image/20231109050118.png','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:01:18','updated_at' => '2024-01-06 07:57:32'),
        //     array('id' => '45','page_id' => '1','hints' => 'whyus-section','title' => 'Located in 5 Countries','subtitle' => NULL,'image' => 'upload/pageContent-image/20231109050206.png','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:02:06','updated_at' => '2024-01-06 07:57:49'),
        //     array('id' => '46','page_id' => '1','hints' => 'whyus-section','title' => '50+ Partner Institutions','subtitle' => NULL,'image' => 'upload/pageContent-image/20231109050302.png','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:03:02','updated_at' => '2024-01-06 07:58:02'),
        //     array('id' => '47','page_id' => '1','hints' => 'whyus-section','title' => 'End to End Services','subtitle' => NULL,'image' => 'upload/pageContent-image/20231109050340.png','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:03:40','updated_at' => '2024-01-06 07:58:13'),
        //     array('id' => '48','page_id' => '1','hints' => 'apply-section','title' => 'Plan Your Best Education in Top Foreign Universities','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:05:17','updated_at' => '2024-01-06 08:20:59'),
        //     array('id' => '59','page_id' => '1','hints' => 'home-contact-social','title' => 'Facebook-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.facebook.com/','is_not_deleteable' => '1','created_at' => '2023-11-09 05:22:33','updated_at' => '2023-11-09 05:22:33'),
        //     array('id' => '60','page_id' => '1','hints' => 'home-contact-social','title' => 'Twitter-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://twitter.com/','is_not_deleteable' => '1','created_at' => '2023-11-09 05:23:11','updated_at' => '2023-11-09 05:23:11'),
        //     array('id' => '61','page_id' => '1','hints' => 'home-contact-social','title' => 'Dribble-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://dribbble.com/','is_not_deleteable' => '1','created_at' => '2023-11-09 05:23:44','updated_at' => '2023-11-09 05:23:44'),
        //     array('id' => '62','page_id' => '1','hints' => 'home-contact-social','title' => 'Instagram-icon','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => 'https://www.instagram.com/','is_not_deleteable' => '1','created_at' => '2023-11-09 05:24:22','updated_at' => '2023-11-09 05:24:22'),
        //     array('id' => '63','page_id' => '1','hints' => 'leading-university','title' => 'Leading Universities','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:25:32','updated_at' => '2024-01-06 10:13:31'),
        //     array('id' => '76','page_id' => '1','hints' => 'blog-news','title' => 'Blog & News','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:39:16','updated_at' => '2023-11-09 05:39:16'),
        //     array('id' => '79','page_id' => '2','hints' => 'About-us-heading','title' => 'ABOUT US','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:48:21','updated_at' => '2024-01-07 07:56:37'),
        //     array('id' => '80','page_id' => '2','hints' => 'About-Button','title' => 'About us','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:51:56','updated_at' => '2024-01-07 07:57:07'),
        //     array('id' => '81','page_id' => '2','hints' => 'About-Button','title' => 'Message From Chairman','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:52:25','updated_at' => '2024-01-07 07:57:14'),
        //     array('id' => '82','page_id' => '2','hints' => 'About-Button','title' => 'Message From Managing Director','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:52:54','updated_at' => '2024-01-07 07:57:20'),
        //     array('id' => '83','page_id' => '2','hints' => 'About-About','title' => 'WH Doctors Study Lab Ltd.','subtitle' => 'We help you to study in Abroad.','image' => 'upload/pageContent-image/20231109055414.png','description' => '<p>STUDY ABROAD also has a well organized platform in Bangladesh for student training for preparation of IELTS and other relevant English language tests. We have liaison branches all over Bangladesh. No other educational training institute in Bangladesh has either such vast network or student access as we do. This exclusive student base we currently have, possesses a great potential for overseas student recruitment. Our various services are comprehensive and tailored to suit students&rsquo; needs and budget. All of our services aim to provide a student with personalized advice and information to help avoid unnecessary expenses until we are confident that Visa application by a student recruited by us has the best possible chance of success.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:54:14','updated_at' => '2024-01-07 07:58:18'),
        //     array('id' => '84','page_id' => '2','hints' => 'About-Mission','title' => 'Our Mission Statement','subtitle' => NULL,'image' => NULL,'description' => '<p>Most educators agree, immersion experiences are among the most lasting, meaningful types of education. Since our founding in 1970, we stand by our mission: &ldquo;International Field Studies is a non-profit organization providing environmental education, scientific research, and cultural awareness through experiential learning.&rdquo;</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:56:14','updated_at' => '2024-01-07 07:55:38'),
        //     array('id' => '85','page_id' => '2','hints' => 'About-What-we-do','title' => 'What We Do','subtitle' => NULL,'image' => NULL,'description' => '<p>International Field Studies, Inc. (IFS) is an educational and scientific non-profit organization established to promote and assist educators with field study programs. Established in 1970, IFS grew out of the increasing teacher interest in implementing field study experiences for their students with minimal organizational difficulty and expense. International Field Studies offers secondary schools, university groups, scientists, and other special-interest organizations field studies in four program areas..... IFS continues to promote the concept of field studies as an important educational method. These experiential, outside of the classroom learning experiences are successful in almost every discipline, including the natural sciences, creative arts, history, and physical education. IFS believes an interdisciplinary approach to learning is especially well suited to the field studies environment. IFS functions as a facilitator for educational groups seeking expertise and logistical support. Staff members, experienced field instructors, and resource materials are available to assist educators and group leaders with educational development, site planning, and budgeting for a successful comprehensive field program. By working with IFS to develop a proposed field study, teachers are able to offer their students high quality field study opportunities.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 05:56:55','updated_at' => '2024-01-07 09:16:05'),
        //     array('id' => '86','page_id' => '2','hints' => 'Sidebar-university-heading','title' => 'Find Your Next Destination...','subtitle' => NULL,'image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 06:04:39','updated_at' => '2024-01-07 09:12:22'),
        //     array('id' => '92','page_id' => '2','hints' => 'Manage-app-heading','title' => 'Manage your projects from your mobile','subtitle' => 'Download the app to manage your projects, keep track of the progress and complete tasks without procastinating. Stay on track and complete on time!','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 06:25:50','updated_at' => '2024-01-07 07:59:13'),
        //     // array('id' => '101','page_id' => '4','hints' => 'Hero section abroad','title' => 'STUDY ABROAD','subtitle' => NULL,'image' => 'upload/pageContent-image/20231109074238.jpeg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 07:42:38','updated_at' => '2024-01-06 12:57:10'),
        //     // array('id' => '103','page_id' => '5','hints' => 'Information section About Button','title' => 'Required Pepper\'s','subtitle' => 'The documents you need for your visa application depend on your situation and the course you are planning to study and the nature of employment of your sponsor. However, in general, you need the following documents:','image' => NULL,'description' => 'A valid LOA (Letter of Acceptance) from a Canadian educational institution','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 07:48:26','updated_at' => '2023-11-09 07:48:26'),
        //     // array('id' => '104','page_id' => '5','hints' => 'Information section About Button','title' => 'Application Information','subtitle' => 'Intakes, English Language Requirements, Diploma - Advanced Diploma','image' => NULL,'description' => 'International students are anticipated to begin planning for their research in Canada one year in advance. The most important intake for Canada usually is \'Fall\' i.e September. The different intake is in the month of \'Winter\' i.e. January, however, it relies upon the program and the institution. Very few institutes have May intake as well.
                                                                                
        //     //                                                                                         All students have to be fluent in English if they\'re applying to Canadian Institutes. International students want to have a specified degree of English language competence. All students ought to take the IELTS or TOEFL(ibt) exams. An IELTS band of 6.5 for Undergraduate & 6.5/7 for Postgraduate publications or a TOEFL rating of eighty and above for Undergraduate and ninety and above for Post Graduate courses is desirable. For Diploma and Advanced Diploma 6.0 in IELTS or equal different tests, a rating is required.
                                                                                
        //     //                                                                                         GPA 3.0 to 5.0 in HSC / Min 4-5C in O Level with C in Math','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 07:50:19','updated_at' => '2023-11-09 07:50:19'),
        //     // array('id' => '105','page_id' => '5','hints' => 'Information section About Button','title' => 'Visa Information','subtitle' => 'Points required to gain Tier four, General Student Visa:','image' => NULL,'description' => 'To efficiently apply for a Tier four General visa, you have to need to score forty out of forty points.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '1','created_at' => '2023-11-09 07:51:01','updated_at' => '2023-11-16 04:10:30'),
        //     array('id' => '107','page_id' => '1','hints' => 'about-section','title' => 'Welcome to WH Doctors Services','subtitle' => 'Lorem ipsum is common placeholder text used to demonstrate','image' => NULL,'description' => '<p>WH Doctor Study Lab is an overseas education consulting firm that helps students to study abroad. Through WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia. The experienced team of WH Doctor Study Lab offers authentic and resourceful information and solutions to students interested in studying abroad. The experienced and well-trained counsellors of WH Doctor Study Lab are dedicated to offering multiple services and help to the students anytime they need it. They have real-life experience studying abroad. Moreover, they get training from the experts to be up-to-date with their knowledge.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-16 06:28:28','updated_at' => '2024-01-06 15:52:36'),
        //     array('id' => '114','page_id' => '1','hints' => 'about-section','title' => 'Welcome to WH Doctors Services Point','subtitle' => 'Lorem ipsum is common placeholder text used to demonstrate','image' => NULL,'description' => '<p>WH Doctor Study Lab is an overseas education consulting firm that helps students to study abroad. Through WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia. The experienced team of WH Doctor Study Lab offers authentic and resourceful information and solutions to students interested in studying abroad. The experienced and well-trained counsellors of WH Doctor Study Lab are dedicated to offering multiple services and help to the students anytime they need it. They have real-life experience studying abroad. Moreover, they get training from the experts to be up-to-date with their knowledge.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-16 06:38:00','updated_at' => '2024-01-06 15:53:52'),
        //     array('id' => '115','page_id' => '1','hints' => 'about-section','title' => 'Welcome to WH Doctors Contact','subtitle' => 'Lorem ipsum is common placeholder text used to demonstrate','image' => NULL,'description' => '<p>WH Doctor Study Lab is an overseas education consulting firm that helps students to study abroad. Through WH Doctor Study Lab, overseas intending students can study in the UK, USA, Canada and Australia. The experienced team of WH Doctor Study Lab offers authentic and resourceful information and solutions to students interested in studying abroad. The experienced and well-trained counsellors of WH Doctor Study Lab are dedicated to offering multiple services and help to the students anytime they need it. They have real-life experience studying abroad. Moreover, they get training from the experts to be up-to-date with their knowledge.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-16 06:38:38','updated_at' => '2024-01-06 15:54:19'),
        //     array('id' => '118','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab 1','subtitle' => 'an education consulting firm','image' => 'upload/pageContent-image/20231210062936.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-01-06 05:59:48'),
        //     array('id' => '119','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab 2','subtitle' => 'an education consulting firm','image' => 'upload/pageContent-image/20231210062946.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-01-06 06:02:06'),
        //     array('id' => '120','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab 3','subtitle' => 'an education consulting firm','image' => 'upload/pageContent-image/20231210062955.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-01-06 06:02:14'),
        //     array('id' => '121','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab 4','subtitle' => 'an education consulting firm','image' => 'upload/pageContent-image/20231210063004.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-01-06 06:02:59'),
        //     array('id' => '122','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab 5','subtitle' => 'an education consulting firm','image' => 'upload/pageContent-image/20231210063013.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-01-06 05:57:26'),
        //     array('id' => '123','page_id' => '1','hints' => 'home-seo','title' => 'WH Doctors Home page','subtitle' => 'WH Doctors, WH, Doctors, Abroad Education','image' => 'upload/pageContent-image/20240108041742.png','description' => 'Description for WH Doctors Home page','number' => NULL,'button_text' => 'seo','button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-01-08 04:17:42','updated_at' => '2024-01-08 04:17:42'),
        //     array('id' => '124','page_id' => '2','hints' => 'about-seo','title' => 'WH Doctors About page','subtitle' => 'WH Doctors, WH, Doctors, Abroad Education','image' => 'upload/pageContent-image/20240108042200.png','description' => 'Description for WH Doctors About page','number' => NULL,'button_text' => 'seo','button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-01-08 04:22:00','updated_at' => '2024-01-08 04:22:00'),
        //     // array('id' => '125','page_id' => '3','hints' => 'service-seo','title' => 'WH Doctors Service Category page','subtitle' => 'WH Doctors, WH, Doctors, Abroad Education, Service Category','image' => 'upload/pageContent-image/20240108042500.png','description' => 'Description for WH Doctors Service Category page','number' => NULL,'button_text' => 'seo','button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-01-08 04:25:00','updated_at' => '2024-01-08 04:25:00'),
        //     array('id' => '126','page_id' => '4','hints' => 'study-abroad-seo','title' => 'WH Doctors Study Abroad page','subtitle' => 'WH Doctors, WH, Doctors, Abroad Education, Study Abroad','image' => 'upload/pageContent-image/20240108043332.png','description' => 'Description for WH Doctors Study abroad page','number' => NULL,'button_text' => 'seo','button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-01-08 04:33:32','updated_at' => '2024-01-08 04:33:32'),
        //     // array('id' => '127','page_id' => '4','hints' => 'abroad-university-seo','title' => 'WH Doctors Abroad University page','subtitle' => 'WH Doctors, WH, Doctors, Abroad Education, Abroad University','image' => 'upload/pageContent-image/20240108044500.png','description' => 'Description for WH Doctors Abroad University page','number' => NULL,'button_text' => 'seo','button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-01-08 04:35:32','updated_at' => '2024-01-08 04:35:32'),
        //     array('id' => '128','page_id' => '1','hints' => 'contact-section','title' => 'Contact Information','subtitle' => 'Fill up the form and our Team will get back to you within 24 hours.','image' => NULL,'description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 08:08:57','updated_at' => '2024-02-04 08:08:57'),
        //     array('id' => '129','page_id' => '9','hints' => 'conference-section','title' => 'Conference','subtitle' => NULL,'image' => NULL,'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 08:57:11','updated_at' => '2024-02-04 08:57:11'),
        //     array('id' => '130','page_id' => '9','hints' => 'conference-seo','title' => 'WH Doctors Conference page','subtitle' => 'WH Doctors, WH, Doctors, Conference','image' => 'upload/pageContent-image/20240204085925.png','description' => 'Description for WH Doctors Conference page','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 08:59:25','updated_at' => '2024-02-04 08:59:25'),
        //     array('id' => '131','page_id' => '10','hints' => 'flybd-section','title' => 'FLY BD','subtitle' => NULL,'image' => NULL,'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 09:03:07','updated_at' => '2024-02-04 09:03:07'),
        //     array('id' => '132','page_id' => '10','hints' => 'flybd-seo','title' => 'WH Doctors FlyBD page','subtitle' => 'WH Doctors, WH, Doctors, FlyBD','image' => 'upload/pageContent-image/20240204090506.png','description' => 'Description for WH Doctors FlyBD page','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 09:05:06','updated_at' => '2024-02-04 09:05:06'),
        //     array('id' => '133','page_id' => '1','hints' => 'service-point','title' => 'Service Point -1','subtitle' => NULL,'image' => NULL,'description' => '<p>In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 10:10:48','updated_at' => '2024-02-04 10:32:45'),
        //     array('id' => '134','page_id' => '1','hints' => 'service-point','title' => 'Service Point -2','subtitle' => NULL,'image' => NULL,'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 10:11:42','updated_at' => '2024-02-04 10:11:42'),
        //     array('id' => '135','page_id' => '1','hints' => 'service-point','title' => 'Service Point -3','subtitle' => NULL,'image' => NULL,'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 10:12:06','updated_at' => '2024-02-04 10:12:06'),
        //     array('id' => '136','page_id' => '1','hints' => 'service-point','title' => 'Service Point -4','subtitle' => NULL,'image' => NULL,'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 10:12:24','updated_at' => '2024-02-04 10:12:24'),

        //     //====================== newly add (13 june, 2014) ===========================
        //     // from page-content where id = (137 to 144)
        //     // delete from page-content where id = (39,40,41,101,102,103,104,105,125,127)
        //     // ===========================================================================

        //     array('id' => '137','page_id' => '1','hints' => 'service-point','title' => 'Service Point -5','subtitle' => NULL,'image' => NULL,'description' => '<p>In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.</p>','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 10:10:48','updated_at' => '2024-02-04 10:32:45'),
        //     array('id' => '138','page_id' => '1','hints' => 'service-point','title' => 'Service Point -6','subtitle' => NULL,'image' => NULL,'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 10:11:42','updated_at' => '2024-02-04 10:11:42'),
        //     array('id' => '139','page_id' => '1','hints' => 'service-point','title' => 'Service Point -7','subtitle' => NULL,'image' => NULL,'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '0','created_at' => '2024-02-04 10:12:06','updated_at' => '2024-02-04 10:12:06'),
        //     array('id' => '140','page_id' => '1','hints' => 'service-point','title' => 'Service Point -8','subtitle' => NULL,'image' => NULL,'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '0','created_at' => '2024-02-04 10:12:24','updated_at' => '2024-02-04 10:12:24'),
        //     array('id' => '141','page_id' => '1','hints' => 'service-point','title' => 'Service Point -9','subtitle' => NULL,'image' => NULL,'description' => 'In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before the final copy is available.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '0','created_at' => '2024-02-04 10:12:24','updated_at' => '2024-02-04 10:12:24'),
        //     array('id' => '142','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab 6','subtitle' => 'an education consulting firm','image' => 'upload/pageContent-image/20231210062965.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','active_status' => '0','created_at' => '2023-11-18 15:02:11','updated_at' => '2024-01-06 05:59:48'),
        //     array('id' => '143','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab 7','subtitle' => 'an education consulting firm','image' => 'upload/pageContent-image/20231210062976.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0', 'active_status' => '0', 'created_at' => '2023-11-18 15:02:11','updated_at' => '2024-01-06 06:02:06'),
        //     array('id' => '144','page_id' => '1','hints' => 'slider','title' => 'WH Doctor Study Lab 8','subtitle' => 'an education consulting firm','image' => 'upload/pageContent-image/20231210062995.jpg','description' => NULL,'number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0', 'active_status' => '0', 'created_at' => '2023-11-18 15:02:11','updated_at' => '2024-01-06 06:02:14'),
        //     array('id' => '145','page_id' => '11','hints' => 'abroad-living-section','title' => 'Abroad Living','subtitle' => NULL,'image' => NULL,'description' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in. Nostrum itaque asperiores ducimus hic a molestias cum perspiciatis. Aut fuga distinctio quis consectetur voluptas explicabo quidem nam debitis error ullam inventore blanditiis, voluptatibus fugiat libero numquam a quae labore excepturi pariatur mollitia ut tempora. Inventore quaerat nihil ipsa aliquam corporis in.','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 09:03:07','updated_at' => '2024-02-04 09:03:07'),
        //     array('id' => '146','page_id' => '11','hints' => 'abroad-living-seo','title' => 'WH Doctors Abroad Living page','subtitle' => 'WH Doctors, WH, Doctors, FlyBD','image' => 'upload/pageContent-image/20240204090506.png','description' => 'Description for WH Doctors FlyBD page','number' => NULL,'button_text' => NULL,'button_link' => NULL,'is_not_deleteable' => '0','created_at' => '2024-02-04 09:05:06','updated_at' => '2024-02-04 09:05:06'),
        // );
        foreach($page_contents as $data)
        {
            PageContent::create($data);
        }
    }
}
