<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\University;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datas = array(
            array('id' => '1','type' => 'private','country_id' => '458','image' => 'upload/university-image/logo/20240519072816.png','cover_image' => NULL,'name' => 'Taylor’s University;','description' => NULL,'address' => '<p>MALAYSIA<a href="http://wh-doctors.we4sell.com/study-abroad-university">&nbsp;http://wh-doctors.we4sell.com/study-abroad-university</a>:&nbsp;</p>

            <p>TEST LINK&nbsp;</p>','program' => 'P.h.D ; Masters  and Bachalors','tuition_fee' => '20000','living_cost' => '2000','application_date' => '2023-12-05','admission_requirements' => '<p>Lorem ipsum is common placeholder text used to demonstrate</p>','is_show_homepage' => '1','is_partner' => '1','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => '/tmp/phpJEQdV7','created_at' => '2023-12-11 08:16:59','updated_at' => '2024-05-19 13:28:16'),
            array('id' => '2','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20240122163722.png','cover_image' => NULL,'name' => 'University of Malaya','description' => NULL,'address' => '<p>Lorem ipsum is common placeholder text used to demonstrate</p>','program' => 'Lorem','tuition_fee' => '8000','living_cost' => '3000','application_date' => '2023-12-01','admission_requirements' => '<p>Lorem ipsum is common placeholder text used to demonstrate</p>','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:17:46','updated_at' => '2024-01-22 22:37:22'),
            array('id' => '4','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211021927.png','cover_image' => NULL,'name' => 'Putra Business School','description' => NULL,'address' => '<p>Lorem ipsum is common placeholder text used to demonstrate</p>','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => '<p>Lorem ipsum is common placeholder text used to demonstrate</p>','is_show_homepage' => '1','is_partner' => '1','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:19:27','updated_at' => '2024-05-11 22:09:55'),
            array('id' => '5','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211022052.png','cover_image' => NULL,'name' => 'MAHSA University','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:20:52','updated_at' => '2023-12-11 08:20:52'),
            array('id' => '6','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211022130.png','cover_image' => NULL,'name' => 'Monash University Malaysia','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:21:30','updated_at' => '2023-12-11 08:21:30'),
            array('id' => '7','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211022206.png','cover_image' => NULL,'name' => 'INTI International University (IIU)','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:22:06','updated_at' => '2023-12-11 08:22:06'),
            array('id' => '8','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211022241.png','cover_image' => NULL,'name' => 'Multimedia University (MMU), Cyberjaya','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:22:41','updated_at' => '2023-12-11 08:22:41'),
            array('id' => '9','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211022543.png','cover_image' => NULL,'name' => 'Limkokwing University of Creative Technology','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:25:43','updated_at' => '2023-12-11 08:51:24'),
            array('id' => '10','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211022620.png','cover_image' => NULL,'name' => 'University Tenaga Nasional (UNITEN)','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:26:20','updated_at' => '2023-12-11 08:26:20'),
            array('id' => '11','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211022707.png','cover_image' => NULL,'name' => 'Asia e University (AeU)','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:27:07','updated_at' => '2023-12-11 08:27:07'),
            array('id' => '12','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211022929.png','cover_image' => NULL,'name' => 'UCSI University','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:29:29','updated_at' => '2023-12-11 08:29:29'),
            array('id' => '14','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211023209.png','cover_image' => NULL,'name' => 'University Teknologi Petronas (UTP)','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '1','is_partner' => '1','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:32:09','updated_at' => '2024-01-06 16:21:36'),
            array('id' => '15','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211023246.png','cover_image' => NULL,'name' => 'University Kuala Lumpur (UniKL)','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:32:46','updated_at' => '2023-12-11 08:32:46'),
            array('id' => '16','type' => 'public','country_id' => '458','image' => NULL,'cover_image' => 'upload/university-image/cover/20231211023350.png','name' => 'Albukhary International University','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:33:50','updated_at' => '2023-12-11 08:33:50'),
            array('id' => '17','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211023426.png','cover_image' => NULL,'name' => 'Al-Madinah International University (MEDIU)','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:34:26','updated_at' => '2023-12-11 08:52:10'),
            array('id' => '18','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211023517.png','cover_image' => NULL,'name' => 'International Centre for Education in Islamic Finance (INCEIF)','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:35:17','updated_at' => '2023-12-11 08:52:48'),
            array('id' => '19','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211023604.png','cover_image' => NULL,'name' => 'Sunway University','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:36:04','updated_at' => '2023-12-11 08:36:04'),
            array('id' => '20','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211023657.png','cover_image' => NULL,'name' => 'Perdana University','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:36:57','updated_at' => '2023-12-11 08:36:57'),
            array('id' => '21','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211023738.png','cover_image' => NULL,'name' => 'HELP University','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:37:38','updated_at' => '2023-12-11 08:37:38'),
            array('id' => '23','type' => 'public','country_id' => '458','image' => '/tmp/phpC6VVrR','cover_image' => NULL,'name' => 'SEGi University, Malaysia','description' => NULL,'address' => '<p>Lorem ipsum is common placeholder text used to demonstrate</p>','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => '<p>Lorem ipsum is common placeholder text used to demonstrate</p>','is_show_homepage' => '1','is_partner' => '1','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => '/tmp/phprqceQd','created_at' => '2023-12-11 08:39:23','updated_at' => '2024-05-11 22:17:41'),
            array('id' => '24','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211024309.png','cover_image' => NULL,'name' => 'Asia Pacific University of Technology and Innovation (APU)','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:43:09','updated_at' => '2023-12-11 08:43:09'),
            array('id' => '25','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211024401.png','cover_image' => NULL,'name' => 'Binary University of Management and Entrepreneurship','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:44:01','updated_at' => '2023-12-11 08:44:01'),
            array('id' => '26','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211024435.png','cover_image' => NULL,'name' => 'Infrastructure University Kuala Lumpur (IUKL)','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:44:35','updated_at' => '2023-12-11 08:44:35'),
            array('id' => '27','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211024719.png','cover_image' => NULL,'name' => 'University Islam Malaysia, Cyberjaya','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:47:19','updated_at' => '2023-12-11 08:47:19'),
            array('id' => '29','type' => 'public','country_id' => '458','image' => 'upload/university-image/logo/20231211120447.png','cover_image' => NULL,'name' => 'Universit Cyberjaya (University of Cyberjaya','description' => NULL,'address' => '<p>Lorem ipsum is common placeholder text used to demonstrate</p>','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => '<p>Lorem ipsum is common placeholder text used to demonstrate</p>','is_show_homepage' => '1','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:49:17','updated_at' => '2024-05-11 22:03:48'),
            array('id' => '30','type' => 'public','country_id' => '4','image' => 'upload/university-image/logo/20240106113252.png','cover_image' => NULL,'name' => 'X','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '1','is_partner' => '1','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:49:17','updated_at' => '2024-01-06 17:32:52'),
            array('id' => '31','type' => 'public','country_id' => '16','image' => 'upload/university-image/logo/20240106113306.png','cover_image' => NULL,'name' => 'Y','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '1','is_partner' => '1','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:49:17','updated_at' => '2024-01-06 17:33:06'),
            array('id' => '33','type' => 'public','country_id' => '50','image' => NULL,'cover_image' => NULL,'name' => 'B','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:49:17','updated_at' => '2023-12-11 08:49:17'),
            array('id' => '34','type' => 'public','country_id' => '554','image' => NULL,'cover_image' => NULL,'name' => 'N','description' => NULL,'address' => 'Lorem ipsum is common placeholder text used to demonstrate','program' => 'Lorem','tuition_fee' => '1000','living_cost' => '1000','application_date' => '2023-12-31','admission_requirements' => 'Lorem ipsum is common placeholder text used to demonstrate','is_show_homepage' => '0','is_partner' => '0','meta_title' => NULL,'meta_keywords' => NULL,'meta_description' => NULL,'meta_image' => NULL,'created_at' => '2023-12-11 08:49:17','updated_at' => '2023-12-11 08:49:17')
        );
        foreach($datas as $data)
        {
            University::create($data);
        }

    }
}
